name: Tests

on: [pull_request]

jobs:
    playwright-test:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
              node-version: 18
          - run: npm install
          - run: npm run build
          - name: Run tests
            run: npm run test-playwright
            #run: xvfb-run --auto-servernum npm run ci
            #working-directory: ./example
            env:
              API_KEY: ${{ secrets.AXE_DEVHUB_API_KEY_MY_REACT_APP }}
              SERVER_URL: ${{ secrets.AXE_DEVHUB_SERVER_MY_REACT_APP }}
    axe-dev-hub:
        runs-on: ubuntu-latest
        needs: playwright-test
        steps:
          - uses: actions/checkout@v3
          - uses: dequelabs/axe-devhub-action@v1
            with:
                api_key: ${{ secrets.AXE_DEVHUB_API_KEY_MY_REACT_APP }}
                server_url: ${{ secrets.AXE_DEVHUB_SERVER_MY_REACT_APP }}